### ISSUE TITLE
Images not rendering

### ISSUE THREAD

**Issue by aburk3** [learn-co-curriculum/review-map-state-to-props-readme#10] opened 2019-05-01 18:17 UTC
<img width="311" alt="Screen Shot 2019-05-01 at 1 16 11 PM" src="https://user-images.githubusercontent.com/24820716/57033756-5fdce000-6c13-11e9-8067-ab4a0b968cbf.png">

**Comment by maxwellbenton** [comment] 2019-09-23 21:53
Hi @aburk3,

Thank you for opening this issue. From the image you provided, it looks like this was a problem with the Learn.co website rather than this lesson specifically. I've taken a look and confirmed that student images on the site are currently loading. 

As there are no images specifically related to this lesson/repository, I'm going to close this issue.

Thank you for contributing to a Learn lesson!

**Closed as completed by maxwellbenton** 2019-09-23 21:53 UTC
